site_name: API
repo_url: https://github.com/carmichaellcs/
repo_name: Teste
edit_uri: tree/main/docs

theme:
  name: material
  language: pt-BR
  # logo: assets/*.png
  # favicon: assets/*.png

markdown_extensions:
  - attr_list

# extra_css:
#   - stlesheets/extra.css